version: '2'
services:
    jhipstersampleapplication55-app:
        image: jhipstersampleapplication55
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplication55-mysql:3306/jhipstersampleapplication55?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersampleapplication55-mysql:
        extends:
            file: mysql.yml
            service: jhipstersampleapplication55-mysql
